name: timezone
description: Time zone database and time zone aware DateTime.
repository: https://github.com/srawlins/timezone
version: 0.10.2

environment:
  sdk: ^3.10.0

dependencies:
  http: ^1.2.1
  path: ^1.8.0

dev_dependencies:
  args: any
  file: '>=6.0.0 <8.0.0'
  glob: ^2.0.0
  lints: ^6.0.0
  logging: ^1.2.0
  test: ^1.16.0
